config/routes.rb
Rails.application.routes.draw do
  

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'account_activations/edit'

  get 'sessions/new'

  root 'static_pages#home'

  get 'help' => 'static_pages#help'

  get 'about' => 'static_pages#about'

  get 'contact' => 'static_pages#contact'
 
 	get 'signup' => 'users#new'

 	get 'login' => 'sessions#new'

 	post 'login' => 'sessions#create'

 	delete 'logout' => 'sessions#destroy'

 	resources :users do
		member do
			get :following, :followers
		end
	end



 	resources :users
 	resources :account_activations, only: [:edit]
 	resources :password_resets,     only: [:new, :create, :edit, :update]
 	resources :microposts,          only: [:create, :destroy]
 	resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.htmlll

end

app/controllers/static_pages_controller.rb
class StaticPagesController < ApplicationController
  def home
  	if logged_in?
  	 @micropost = current_user.microposts.build 
  	 @feed_items = current_user.feed.paginate(page: params[:page])
    end 
 end

  def help
  end

  def about 
  end 

  def contact 
  end 
end

app/helpers/static_pages_helper.rb
module StaticPagesHelper
end

app/views/static_pages/about.html.erb
<% provide(:title,"About") %>
<h1>About</h1>
<p>this is the about page</p>

app/views/static_pages/contact.html.erb
<%= provide(:title,"Contact") %>
<h1> Contact </h1>

app/views/static_pages/help.html.erb
<% provide(:title,"Help") %>
<h1>Help</h1>
<p>this is the help page</p>

app/views/static_pages/home.html.erb
<% if logged_in? %>
	<div class="row">
		<aside class="col-md-4">
			<section class="user_info">
				<%= render 'shared/user_info' %>
			</section>
			<section class="stats">
				<%= render 'shared/stats' %>
			</section>
			<section class="micropost_form">
				<%= render 'shared/micropost_form' %>
			</section> 
		</aside>
		<div class="col-md-8">
			<h3>Micropost Feed</h3>
			<%= render 'shared/feed' %>
		</div>
	</div>
	<% else %>
		<div class="center jumbotron">

			<h1>Welcome to the Sample app</h1>
			<p>this is the home page</p>
				<%= link_to "Sign up now!", signup_path, class: "btn btn-lg btn-primary" %>

		</div>

				<%= link_to image_tag("rails.png", alt: "rails logo"), 'http://rubyonrails.org' %>

<% end %>


	