config/routes.rb
Rails.application.routes.draw do
  

  get 'password_resets/new'

  get 'password_resets/edit'

  get 'account_activations/edit'

  get 'sessions/new'

  root 'static_pages#home'

  get 'help' => 'static_pages#help'

  get 'about' => 'static_pages#about'

  get 'contact' => 'static_pages#contact'
 
 	get 'signup' => 'users#new'

 	get 'login' => 'sessions#new'

 	post 'login' => 'sessions#create'

 	delete 'logout' => 'sessions#destroy'

 	resources :users do
		member do
			get :following, :followers
		end
	end



 	resources :users
 	resources :account_activations, only: [:edit]
 	resources :password_resets,     only: [:new, :create, :edit, :update]
 	resources :microposts,          only: [:create, :destroy]
 	resources :relationships, only: [:create, :destroy]
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.htmlll

end

app/views/shared/_error_messages.html.erb
<% if object.errors.any? %>
	<div id="error_explanation">
		<div class="alert alert-danger">
			The form contains <%= pluralize(object.errors.count, "error") %>.
		</div>
		<ul>
			<% object.errors.full_messages.each do |msg| %>
				<li><%= msg %></li>

			<% end %>
		</ul>
  </div>

<% end %>

app/views/shared/_feed.html.erb
<% if @feed_items.any? %>
	<ol class="microposts">
		<%= render @feed_items %>
	</ol>
	<%= will_paginate @feed_items %>
	<% end %>

app/views/shared/_footer.html.erb
<footer class="footer">
<nav>
	<ul>
		<li><%= link_to "About", about_path %></li>
		<li><%= link_to "Contact", contact_path %></li>
	</ul>
</nav>
</footer>

app/views/shared/_header.html.erb
<header class ="navbar navbar-fixed-top navbar-inverse">
		
		<div class = "container">

			<%= link_to"sample app", root_path, id: "logo" %>	
			<nav>
				<ul class= "nav navbar-nav pull-right">
					<li><%= link_to "Home",   root_path %></li>
					<li><%= link_to "Help",   help_path %></li>
					<li><%= link_to "About",  about_path %></li>
					<% if logged_in? %>
						<li><%= link_to "Users", users_path %></li>
						<li class="dropdown">
							<a href="#" class="dropdown-toggle" data-toggle="dropdown">
								Account <b class="caret"></b>
							</a>
							<ul class="dropdown-menu">
								<li><%= link_to "Profile", current_user %></li>
								<li><%= link_to "Settings", edit_user_path(current_user) %></li>
								<li class="divider"></li>
								<li>
										<%= link_to "Log out", logout_path, method: "delete" %>
								</li>
							</ul>

						</li>
					<% else %>
						<li><%= link_to "Log in", login_path %></li>
					<% end %>
				</ul>
			</nav>
		</div>
</header>

app/views/shared/_micropost_form.html.erb
<%= form_for(@micropost, html:{ multipart: true }) do |f| %>
<%= render 'shared/error_messages', object: f.object %>
	<div class="field">
		<%= f.text_area :content, placeholder: "Compose new micropost.." %>

	</div>
	<%= f.submit "Post", class: "btn btn-primary" %>
	<span class="picture">
		<%= f.file_field :picture, accept: 'image/jpeg,image/gif,image/png' %>
	</span>
	<% end %>

<script type="text/javascript">
  $('#micropost_picture').bind('change', function() {
    var size_in_megabytes = this.files[0].size/1024/1024;
    if (size_in_megabytes > 5) {
      alert('Maximum file size is 5MB. Please choose a smaller file.');
    }
  });
</script>

app/views/shared/_shim.html.erb
<!--[if lt IE 9]>
	<script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
	</script>
	<![endif]-->

app/views/shared/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
	<a href="<%= following_user_path(@user) %>">
		<strong id="following" class="stat">
			<%= @user.following.count %>
		</strong>
		following
	</a>
	<a href="<%= followers_user_path(@user) %>">
		<strong id="followers" class="stat">
			<%= @user.followers.count %>
		</strong>
		followers
	</a>
</div>

app/views/shared/_user_info.html.erb
<%= link_to gravatar_for(current_user, size:50),current_user %>
<h1><%= current_user.name %></h1>
<span><%= link_to "view my profile", current_user %></span>
<span><%= pluralize(current_user.microposts.count, "micropost") %> </span>